
CREATE TABLE USERS (
	ID INT(11) NOT NULL COMMENT 'Primary Key',
	USER_NAME VARCHAR(50) NOT NULL COMMENT 'User Id',
	First_Name VARCHAR(50) NOT NULL COMMENT 'First name of user',
	LAST_NAME VARCHAR(50) NOT NULL COMMENT 'Last Name ',
	PRIMARY KEY (ID),
	UNIQUE INDEX USER_NAME (USER_NAME)
)
COMMENT='To store portal USER details';

CREATE TABLE ROLES (
	ID INT(11) NOT NULL COMMENT 'Roe Id',
	ROLE_NAME VARCHAR(50) NOT NULL COMMENT 'Role Name',
	DESCRIPTION VARCHAR(50) NOT NULL COMMENT 'Role Description',
	PRIMARY KEY (ID),
	UNIQUE INDEX ROLE_NAME (ROLE_NAME)
)
COMMENT='To store portal ROLES details';

CREATE TABLE USER_ROLES (
	ID INT(11) NOT NULL COMMENT 'Primary Key',
	USER_ID INT(11) NOT NULL COMMENT 'Foriegn key',
	ROLE_ID INT(11) NOT NULL COMMENT 'Foriegn Key Roles',
	PRIMARY KEY (ID),
	INDEX FK_USER_ID (USER_ID),
	INDEX FR_ROLE_ID (ROLE_ID),
	CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES users (ID) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FR_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES roles (ID) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COMMENT='Users and Roles Mapping';

